name: Docker

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - "main"
    tags:
      - "*.*.*"
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
          ROS_DISTRO: [humble, jazzy, rolling]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/synapticon_ros2_control
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule, pattern=latest
            type=ref,event=branch
            type=ref,event=tag

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=${{matrix.ROS_DISTRO}}
          push: ${{ github.event_name != 'pull_request' }} # only push from non-pull_request triggers
          #tags: ghcr.io/synapticon/synapticon_ros2_control:latest --> replaced by docker/metadata-action config
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
